data: data/ZhEn_1w/hdf5_mfcc_noisy/train_1w.csv
label: data/ZhEn_1w/softlabels/train.csv
hard_label: data/ZhEn_1w/hardlabels/train.label
batch_size: 16
data_args:
    mode: Null
num_workers: 1
optimizer: AdamW
optimizer_args:
    lr: 0.001
scheduler_args:
    patience: 10
    factor: 0.1
early_stop: 10
epochs: 30
iter_cv: 10
iter_save_ckpt: 20
save: best
model: CRNN
model_args: {}
outputpath: experiments/CRNN/ZhEn-3k-0.8noisy-vad-debug
transforms: [timemask, freqmask]
loss: ClipFrameHardSoftBCELoss #FrameBCELoss
pretrained: experiments/CRNN/ZhEn-3k-0.8noisy-vad/run_model_loss=-1.0194.pt
